image: archlinux

packages:
  - python-setuptools
  - poetry

sources:
  - https://github.com/nhanb/fundoshi.git#reorg

tasks:

  - setup: |
      cd fundoshi
      poetry install

  - test: |
      cd fundoshi
      make test

  ## Workaround for lack of built-in branch check:
  ## https://todo.sr.ht/~sircmpwn/builds.sr.ht/170
  - check-branch: |
      cd fundoshi
      if [[ "$GITHUB_EVENT" != 'push' ]] || [[ ! "$GITHUB_REF" =~ '^refs/tags/' ]]; then \
        complete-build; \
      fi


  - deploy: |
      cd fundoshi
      echo "I'm DEPLOYING"

secrets:
  - b460cca6-77a9-4041-b928-b781b3b3f6ab
